version: '3'
services:
  balancer:
    image: "jwilder/nginx-proxy"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
        - 80:80
    restart: "no"

  www:
    image: "dev.dreams.es:4567/dreams/docker-php:7.1-xdebug"
    volumes:
      - .:/var/www/html
    dns: 192.168.1.201
    dns_search: 192.168.1.201
    hostname: langtranslator.dreams
    environment:
      - VIRTUAL_HOST=langtranslator.dreams
      - user=jorge
    restart: "no"